# Generated by Django 5.1.6 on 2025-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=100)),
                ('prescription_date', models.DateField()),
                ('dosage', models.IntegerField()),
            ],
        ),
    ]
