# Generated by Django 5.1.6 on 2025-04-07 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treatement', '0002_alter_prescription_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
